import os, sys
Import('env')
env = env.Clone()

cpps = Glob("*.cpp")
lib = env.SharedLibrary(target = "add_tool",
        source = cpps)
env.Install(env["build_lib_path"], lib)
SConscript("test/SConscript")

header_install_dir = [env['install_head_root']  + "util/"]
env.Install(header_install_dir, Glob("*.h"))
env.Install(env["install_lib_root"], lib)

